include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - macros

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_function_literals_in_foreach_calls: false

